name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
projects: ["group11sem/ set08103"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: version
    attributes:
        label: Database
        description: What database were you accessing?
        options:
          - World
        default: 0
    validations:
        required: true
  - type: input
    id: contact
    attributes:
      label: Information Attempting to access?
      description: What kind of information were you trying to access from the database?
      placeholder: ex. Top 5 populated countries in Asia.
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Issue?
      description: What problem occurred when trying to access data?
      options:
        - Error
        - Wrong information
        - other
      default: 0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened when you tried accessing that information?
      description: Did an error occur, not the correct output, or some other wacky outcome?
      placeholder: Type your response here.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant output data
      description: Please copy and paste any relevant log output. This will give us more insight into the specific issue.
      render: shell
