name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
projects: ["group11sem/set08103"]
assignees:
  - group11
body:
  - type: dropdown
    id: database
    attributes:
      label: Database?
      description: What database were you using?
      options:
        - World
      default: 0
    validations:
      required: true
  - type: input
    id: information
    attributes:
      label: What information were you trying to access?
      placeholder: ex. Top 5 populated countries in Asia.
    validations:
      required: false
  - type: dropdown
    id: issue
    attributes:
      label: Issue
      description: What problem did you encounter?
      options:
        - Error
        - Incorrect Information
        - Other
      default: 0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What was the outcome?
      description: What happened when you tried searching and what did you expect to occur?
      placeholder: Type answer here.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Output data
      description: Please copy pasta your data from the output log here to give us a better understanding of what happened.
      render: shell
