name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
projects: ["group11sem/ set08103"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Information Attempting to access?
      description: What kind of information were you trying to access from the database?
      placeholder: ex. Top 5 populated countries in Asia.
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened when you tried accessing that information?
      description: Did an error occur, not the correct output, or some other wacky outcome?
      placeholder: Type your response here.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
